name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      
      - name: Install dependencies
        run: npm install
      
      - name: Check for missing files
        run: |
          if [ ! -f "public/index.html" ]; then
            echo "Creating index.html file..."
            mkdir -p public
            cat > public/index.html << 'EOL'
          <!DOCTYPE html>
          <html lang="en">
            <head>
              <meta charset="utf-8" />
              <link rel="icon" href="%PUBLIC_URL%/favicon.ico" />
              <meta name="viewport" content="width=device-width, initial-scale=1" />
              <meta name="theme-color" content="#000000" />
              <meta
                name="description"
                content="AHDB FarmAssist - Farm management tools and resources"
              />
              <link rel="apple-touch-icon" href="%PUBLIC_URL%/logo192.png" />
              <link rel="manifest" href="%PUBLIC_URL%/manifest.json" />
              <title>AHDB FarmAssist</title>
            </head>
            <body>
              <noscript>You need to enable JavaScript to run this app.</noscript>
              <div id="root"></div>
            </body>
          </html>
          EOL
          fi

          if [ ! -f "public/manifest.json" ]; then
            echo "Creating manifest.json file..."
            cat > public/manifest.json << 'EOL'
          {
            "short_name": "AHDB FarmAssist",
            "name": "AHDB FarmAssist App",
            "icons": [
              {
                "src": "favicon.ico",
                "sizes": "64x64 32x32 24x24 16x16",
                "type": "image/x-icon"
              }
            ],
            "start_url": ".",
            "display": "standalone",
            "theme_color": "#000000",
            "background_color": "#ffffff"
          }
          EOL
          fi

          if [ ! -f "staticwebapp.config.json" ]; then
            echo "Creating staticwebapp.config.json file..."
            cat > staticwebapp.config.json << 'EOL'
          {
            "navigationFallback": {
              "rewrite": "/index.html",
              "exclude": ["/images/*.{png,jpg,gif}", "/css/*", "/js/*", "/assets/*"]
            },
            "routes": [
              {
                "route": "/*",
                "serve": "/index.html",
                "statusCode": 200
              }
            ],
            "mimeTypes": {
              ".json": "text/json"
            },
            "globalHeaders": {
              "Cache-Control": "no-cache"
            }
          }
          EOL
          fi

          if [ ! -f "public/favicon.ico" ]; then
            echo "Creating placeholder favicon.ico..."
            touch public/favicon.ico
          fi
      
      - name: Build with ESLint disabled
        run: |
          echo "Building React app with ESLint disabled..."
          DISABLE_ESLINT_PLUGIN=true npm run build
        env:
          CI: false
      
      # Check if build directory exists and has index.html
      - name: Verify build output
        run: |
          if [ ! -f "build/index.html" ]; then
            echo "Error: build/index.html not found! Contents of build directory:"
            ls -la build || echo "build directory doesn't exist!"
            exit 1
          else
            echo "Build directory contains:"
            ls -la build
          fi
      
      - name: Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          # Use the specific token name provided
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ZEALOUS_BUSH_087AEB003 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/build"  # Points to the build directory
          api_location: "" 
          output_location: ""
          
  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          # Use the specific token name here too
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ZEALOUS_BUSH_087AEB003 }}
          action: "close"
